spring.application.name=eureka-server

# --- Server Configuration ---
# El puerto estándar y recomendado para Eureka Server es 8761.
server.port=8761

# --- Eureka Server Specific Configuration ---
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# --- Eureka Instance Configuration (Detalles de cómo se identifica esta instancia) ---
eureka.instance.hostname=localhost
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# --- Web UI Configuration (Configuración de la interfaz de usuario de Eureka) ---
eureka.dashboard.title=Gestor de Inventario - Eureka Service Registry

# --- Actuator Configuration (para monitoreo y gestión del propio Eureka Server) ---
management.endpoints.web.exposure.include=*